[16.0][MIG]connector dns
OCA/infrastructure pull request #18
Opened 2022-12-26 12:23 UTC by flotho

trying a standard port with oca-port

2022-12-26 22:40 UTC, flotho commented
Hi,
I would like to submit for a first review this PR to check if I'm going in the right direction.
@lasley @noahzaozao @ruter-lyu @murtuzasaleh @max3903 @JoJoJoJoJoJoJo all comments would will be appreciated.

The next step will be to create connector modules, I will start with an OVH connector

2022-12-26 22:44 UTC, flotho commented
ping @sbidoul there's an issue during the build and I'm not able to identify the origin.
Regards

2022-12-30 10:33 UTC, flotho commented
here is the logs that I can't see what to to from my side : 
```
ERROR: Cannot install odoo<16.1dev and >=16.0a and odoo<9.0a and >=8.0a because these package versions have conflicting dependencies.

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
The conflict is caused by:
    The user requested odoo<16.1dev and >=16.0a
    The user requested odoo<9.0a and >=8.0a
```

2022-12-30 11:39 UTC, sbidoul commented
Hi @flotho! That is because there is a [manifest with version 8.0](https://github.com/OCA/infrastructure/pull/18/files#diff-c2e0f92cd369f25bb042e530081acb0378824ebf349cc811553eb4ae075abd37R7) in this PR. Addons with such manifest automatically depend on Odoo 8 and pip cannot satisfy that in a 16.0 branch CI.

2022-12-30 12:35 UTC, flotho commented
thanks @sbidoul , I'll check this

2023-01-04 14:32 UTC, flotho commented
Hi @lasley @noahzaozao @ruter-lyu @murtuzasaleh @max3903 @JoJoJoJoJoJoJo 

I'm rebooting this repo in v16 with a simple module as a strating point.
Everything is green here
The next step will be to create connector modules, 
Please feel free to comment and reviw.

Thanks

2023-11-03 21:19 UTC, bosd commented
Can you fix pre-commit?

2023-11-04 15:19 UTC, flotho commented
> Can you fix pre-commit?

with pleasure,
Done !

2023-11-04 17:08 UTC, flotho commented
hum @bosd , did I miss something on the pylint issue?
Not sur I can do something here!

2023-11-16 17:54 UTC, bosd commented
> hum @bosd , did I miss something on the pylint issue?
> Not sur I can do something here!

Hmm, maybe this repo needs an update with `copier update`

2024-05-25 20:51 UTC, flotho commented
> > hum @bosd , did I miss something on the pylint issue?
> > Not sur I can do something here!
> 
> Hmm, maybe this repo needs an update with `copier update`

Thanks for the proposal, sadly the command `copier update` failed. Do you have any tips/doc/recommandation on how to use copier in OCA projects ?

2024-05-25 21:08 UTC, flotho commented
not sure to understand what's wrong in this pre commit

2024-05-25 21:09 UTC, bosd commented
Ooh I think the copier update' of the repo has already been done recently.

Try rebasing your branch. That should fix it.

2024-05-25 22:05 UTC, bosd requested changes
very quick code review. The suggested changes should make gh actions happy. :green_heart:

2024-05-25 22:05 UTC, bosd commented on base_dns_infrastructure/__manifest__.py
> +        "python": ["validator_collection"],
```suggestion
        "python": ["validator-collection"],
```

2024-05-25 22:05 UTC, bosd commented on requirements.txt
> +validator_collection
```suggestion
validator-collection
```

2024-05-25 22:05 UTC, bosd commented on .pylintrc-mandatory
Why change any of the `.` dotfiles?
Maybe better to exclude the changes, for the CI.

2024-05-25 22:05 UTC, bosd commented on base_dns_infrastructure/static/description/icon.png
You can replace (overwrite) this file, with the new icon you created.

2024-05-25 22:05 UTC, bosd commented on base_dns_infrastructure/data/dns_record_type.xml
> +        <field name="name">Infrastructure et DNS</field>
```suggestion
        <field name="name">Infrastructure and DNS</field>
```

2024-05-26 09:21 UTC, flotho commented
closed in favor of https://github.com/OCA/infrastructure/pull/20

2024-05-26 09:21 UTC, closed without merging